### ISSUE TITLE
Custom custom locations are not well supported by spacemacs

### ISSUE THREAD

**Issue by jellelicht** [mickvangelderen/.spacemacs.d#1]
Spacemacs (at least the develop branch) does not properly handle custom custom locations, as set via:  
`(setq custom-file "~/.spacemacs.d/custom.el")`.

See [this spacemacs issue](https://github.com/syl20bnr/spacemacs/issues/1639#issuecomment-266332271) .  

(I had some issues with this using directory local variables via a custom.el in the project root. )

**Comment by ghost** [comment]
@jellelicht @mickvangelderen Custom file is now possible with latest develop version of Spacemacs, see this example:

https://github.com/SteveJobzniak/spacemaxed/commit/e39f8f5b4747ebf7cb9801fd9b8b13e435acb348
